### ISSUE TITLE
Setup nuget publication process

### ISSUE THREAD

**Issue by HarryMcCarney** [fslaborg/Graphoscope#20]
We need to process for automating the publishing of nuget packages from sprint releases.
    
This will make Michele's testing feedback easier (he can reference the current version in fsx rather than having to build locally) and I think rapid iterative publication will improve quality faster.

I think we could publish v0.1 to the public nuget feed.    Clearly we will need to caveat it with "alpha version - unfit for consumption" etc. Alternatively we could use a private package manager. 

Happy to discuss.

**Comment by kMutagene** [comment]
I think we can close this, as the package is live 🎉
