### ISSUE TITLE
Implement Watts-Strogatz Model for Small-World Networks

### ISSUE THREAD

**Issue by LibraChris** [fslaborg/Graphoscope#44]
# Overview:
The Watts-Strogatz model, introduced by Duncan J. Watts and Steven Strogatz in 1998, is a fundamental concept in network science and complex systems. It allows us to simulate and understand small-world networks, which possess unique characteristics including high local clustering and short average path lengths between nodes.

# Problem Statement:
We need to implement the Watts-Strogatz model to create small-world networks within our project. This model will be invaluable for studying network structures in various applications such as social networks, transportation systems, and more.

# Expected Behavior:

### Create a regular lattice network as the starting point.
Implement a random rewiring process with a parameter 'p' to introduce randomness.
Ensure that, as 'p' varies from 0 to 1, the network transitions from a regular lattice to a small-world network with shorter average path lengths while maintaining high local clustering.

### Acceptance Criteria:

 

- [ ] Code implementation of the Watts-Strogatz model.

 

- [ ] Ability to configure the 'p' parameter to control the level of randomness.

 

- [ ] Verify that the model generates networks with appropriate small-world characteristics.

### Additional Information:
The Watts-Strogatz model has wide-ranging applications in fields such as sociology, epidemiology, and network analysis. Implementing this model will enhance our project's capability to simulate and analyze complex systems and networks.

### Sources

- https://en.wikipedia.org/wiki/Watts–Strogatz_model
- http://worrydream.com/refs/Watts-CollectiveDynamicsOfSmallWorldNetworks.pdf

**Comment by HarryMcCarney** [comment]
https://github.com/fslaborg/Graphoscope/pull/55
