### ISSUE TITLE
Implement wedge count

### ISSUE THREAD

**Issue by LibraChris** [fslaborg/Graphoscope#49]
**Description**
The Wedge Count algorithm, like the Triangle Count algorithm, is a graph analysis technique used to identify certain structural patterns within a graph. In this case, it focuses on detecting wedges. A wedge (sometimes called Triad) is a collection of three nodes in the graph where two of these nodes share a direct edge or relationship, and the third node serves as a common neighbour to the other two. This concept is often referred to as a "2-clique" in graph theory.

![image](https://github.com/fslaborg/Graphoscope/assets/59606965/da38e9f3-41d9-4896-81d4-71a0f6c96395)

**Pointers**
[The clustering coefficient ](https://github.com/fslaborg/Graphoscope/blob/1d6f5b9b2336d804faab682c76207fda70672d14/src/Graphoscope/Measures/ClusteringCoefficient.fs#L15) makes use of triangles, which might give some ideas about the implementation.

**References**
- http://konect.cc/statistics/twostars/

**Comment by lamg** [comment]
I'm working on this 🦾

**Comment by DoganCK** [comment]
https://arxiv.org/pdf/1603.05843.pdf

**Comment by LibraChris** [comment]
Another resource:

http://dx.doi.org/10.1137/1.9781611972832.2
